[tool.ruff]
line-length = 120
extend-exclude = [
    ".venv",
    "build",
    "dist",
    "downloaded_data",
    "rivretrieve.egg-info",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "W",  # pycodestyle warnings
    "I",  # isort
]

[tool.ruff.lint.per-file-ignores]
"rivretrieve/__init__.py" = ["F401"]
"rivretrieve/chile.py" = ["E501"]  # The url is too long but can't be splitted.
"docs/conf.py" = ["E402"]  # rivretrieve can't be imported before path is added.